describe("match.virtual", function()
  local t, is, match
  setup(function()
    t = require "t"
    is = t.is
    match = t.match
  end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(table))
    assert.truthy(is.callable(match.virtual))
  end)
  it("positive", function()
    local path = 'testdata/def simpledef'
    local base, name = match.virtual(path)
    assert.equal('testdata/def', base)
    assert.equal('simpledef', name)
    assert.equal(path, '%s %s'%{path:sub(1,#path-#name-1),name})
  end)
  it("negative", function()
    assert.is_nil(match.virtual('meta'))
    assert.is_nil(match.virtual(''))
    assert.is_nil(match.virtual(' '))
    assert.is_nil(match.virtual('  '))
    assert.is_nil(match.virtual('   '))
    assert.is_nil(match.virtual('    '))
    assert.is_nil(match.virtual(true))
    assert.is_nil(match.virtual(false))
  end)
  it("nil", function()
    assert.is_nil(match.virtual())
    assert.is_nil(match.virtual(nil))
  end)
end)