describe("escape/unescape", function()
  local t, escape, unescape
  setup(function()
    t = require "t"
    escape = t.storage.mongo.escape
    unescape = t.storage.mongo.unescape
  end)
  it("escape", function()
    assert.is_nil(escape())
    assert.is_nil(escape(nil))
    assert.is_nil(escape(''))
    assert.equal('any %24 to', escape('any $ to'))
    assert.equal('%3A', escape(':'))
    assert.equal('%2F', escape('/'))
    assert.equal('%3F', escape('?'))
    assert.equal('%23', escape('#'))
    assert.equal('%5B', escape('['))
    assert.equal('%5D', escape(']'))
    assert.equal('%40', escape('@'))
  end)
  it("unescape", function()
    assert.is_nil(unescape())
    assert.is_nil(unescape(nil))
    assert.is_nil(unescape(''))
    assert.equal(':', unescape('%3A'))
    assert.equal('/', unescape('%2F'))
    assert.equal('?', unescape('%3F'))
    assert.equal('#', unescape('%23'))
    assert.equal('[', unescape('%5B'))
    assert.equal(']', unescape('%5D'))
    assert.equal('@', unescape('%40'))
    assert.equal('$', unescape('%24'))
    assert.equal('any $ to', unescape('any %24 to'))
  end)
  it("unescape(escape(.))", function()
    assert.is_nil(unescape(escape('')))
    assert.equal('-- $ : / ? # [ ] @', unescape(escape('-- $ : / ? # [ ] @')))
    assert.equal('-- $ : / ? # [ ] @ zl2ihf2lfh', unescape(escape('-- $ : / ? # [ ] @ zl2ihf2lfh')))
  end)
end)
