name: publish
on:
  push:
    branches:
      - main
    paths:
      - '**.rockspec'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      ROCKSPEC: ${{ github.event.repository.name }}-scm-0.rockspec
    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.1"
    - uses: leafo/gh-actions-luarocks@v4
    - name: publish
      run: |
        luarocks install lua-cjson
        luarocks install luasec
        luarocks upload --force --api-key=${{ env.LUAROCKS_API_KEY }} ${{ env.ROCKSPEC }}
      env:
        LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
