name: test
on:
  push:
    branches:
      - main
    paths:
      - '**.lua'
      - '**.t'
      - '**.yml'
      - '**.rockspec'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "luajit", "luajit-openresty"]
    env:
      DEV: --dev
      SYSDEPS: libmongoc-dev
      ROCKSPEC: ${{ github.event.repository.name }}-scm-0.rockspec
    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - uses: leafo/gh-actions-luarocks@v4
    - name: test deps
      run: luarocks test --prepare ${{ env.DEV }}
    - name: system dependencies
      run: sudo apt update -y && sudo apt install -y ${{ env.SYSDEPS }}
    - name: dependencies
      run: luarocks install --deps-mode all --only-deps ${{ env.DEV }} ${{ env.ROCKSPEC }}
    - name: build
      run: luarocks build --deps-mode all ${{ env.DEV }} ${{ env.ROCKSPEC }}
    - name: docker compose up
      run: docker compose up -d --wait --wait-timeout 10 --no-log-prefix
    - name: docker logs
      run: docker compose logs && docker compose ps
    - name: test
      run: luarocks test -- -o TAP
    - name: docker compose down
      run: docker compose down --remove-orphans -v
